apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/blanc-project/ru-study-app # not live until the source repo actually transfers there
    newTag: afc1afa64f8b877db3887e07ac0f4873654b3a01
