apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/blanc-project/ru-study-app # not live until the source repo actually transfers there
    newTag: 8b09230ea08be0a783dd98bea4661ace11bb5cd5
