apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/blanc-project/ru-study-app # not live until the source repo actually transfers there
    newTag: d69590930d7fcb7ba5c45f32196e4601b0b8e7a6
