apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ru-study-cache
  namespace: ru-study
  labels:
    app.kubernetes.io/name: ru-study
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
