apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ru-study
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blanc-project/ru-study-deploy
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: ru-study
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
