apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: ru-study
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: ru-study.app
        service: http://ru-study.ru-study.svc.cluster.local:80
      - service: http_status:404
